name: Build, Test & Publish

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'

      - name: Run tests with JaCoCo
        run: ./gradlew test jacocoTestReport

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test

  publish:
    name: Publish Code Coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download JaCoCo report
        uses: actions/download-artifact@v5
        with:
          name: jacoco-report
          path: build/reports/jacoco/test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: build/reports/jacoco/test/html/badges

      - name: Publish coverage report to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/jacoco/test/html
          token: ${{ secrets.GITHUB_TOKEN }}