name: Send Telegram Message

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOPIC_ID:
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d message_thread_id=${{ secrets.TELEGRAM_TOPIC_ID }} \
            -d text="${{ inputs.message }}"
